#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔄 Starting Fresh Blockchain...${NC}"

# Stop any running processes
echo -e "${YELLOW}Stopping existing processes...${NC}"
pkill -f mychaind 2>/dev/null || true
pkill -f "npm.*start" 2>/dev/null || true
pkill -f "node.*react" 2>/dev/null || true
sleep 2

# Clean up data
echo -e "${YELLOW}Cleaning up blockchain data...${NC}"
rm -rf ~/.mychain

# Change to project directory
cd "$(dirname "$0")/.."

# Run initialization
echo -e "${BLUE}Initializing blockchain...${NC}"
./scripts/init_chain.sh

# Start the node
echo -e "${BLUE}Starting node...${NC}"
nohup mychaind start > ~/.mychain/node.log 2>&1 &
NODE_PID=$!

echo -e "${YELLOW}Waiting for node to start...${NC}"
sleep 10

# Check if node is running
if ! ps -p $NODE_PID > /dev/null; then
    echo -e "${RED}❌ Node failed to start. Check logs:${NC}"
    tail -n 20 ~/.mychain/node.log
    exit 1
fi

# Initialize MainCoin module by making a small purchase
echo -e "${BLUE}Initializing MainCoin module...${NC}"
sleep 5
mychaind tx maincoin buy-maincoin 1utestusd --from admin --keyring-backend test --chain-id mychain --gas auto --gas-adjustment 1.5 --gas-prices 0.025alc -y > /dev/null 2>&1

sleep 5

# Verify MainCoin initialization
PRICE_CHECK=$(curl -s http://localhost:1317/mychain/maincoin/v1/current_price 2>/dev/null | grep -o '"price"')
if [ -n "$PRICE_CHECK" ]; then
    echo -e "${GREEN}✅ MainCoin module initialized successfully${NC}"
else
    echo -e "${YELLOW}⚠️  MainCoin module may need manual initialization${NC}"
fi

# Start web dashboard
echo -e "${BLUE}Starting web dashboard...${NC}"
cd web-dashboard
nohup npm start > ~/web-dashboard.log 2>&1 &
WEB_PID=$!

echo -e "${YELLOW}Waiting for web dashboard...${NC}"
sleep 10

# Check if dashboard is running
if lsof -i :3000 > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Web dashboard started successfully${NC}"
else
    echo -e "${RED}❌ Web dashboard failed to start${NC}"
fi

echo -e "${GREEN}✨ Blockchain setup complete!${NC}"
echo ""
echo -e "${BLUE}Access Points:${NC}"
echo "   • Web Dashboard: http://localhost:3000"
echo "   • REST API: http://localhost:1317"
echo "   • RPC: http://localhost:26657"
echo ""
echo -e "${BLUE}Useful Commands:${NC}"
echo "   • View logs: tail -f ~/.mychain/node.log"
echo "   • Check status: mychaind status"
echo "   • Stop node: pkill -f mychaind"
echo ""
echo -e "${YELLOW}Note: Direct Execution is disabled by default in the dashboard.${NC}"
echo -e "${YELLOW}Use the CLI commands generated by the dashboard to execute transactions.${NC}"