// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mychain/maincoin/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2f50e7843e7310, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2f50e7843e7310, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgBuyMaincoin defines the MsgBuyMaincoin message.
type MsgBuyMaincoin struct {
	Buyer  string     `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Amount types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
}

func (m *MsgBuyMaincoin) Reset()         { *m = MsgBuyMaincoin{} }
func (m *MsgBuyMaincoin) String() string { return proto.CompactTextString(m) }
func (*MsgBuyMaincoin) ProtoMessage()    {}
func (*MsgBuyMaincoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2f50e7843e7310, []int{2}
}
func (m *MsgBuyMaincoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuyMaincoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuyMaincoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuyMaincoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuyMaincoin.Merge(m, src)
}
func (m *MsgBuyMaincoin) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuyMaincoin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuyMaincoin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuyMaincoin proto.InternalMessageInfo

func (m *MsgBuyMaincoin) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *MsgBuyMaincoin) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// SegmentPurchase represents a purchase within a single segment
type SegmentPurchase struct {
	SegmentNumber uint64 `protobuf:"varint,1,opt,name=segment_number,json=segmentNumber,proto3" json:"segment_number,omitempty"`
	TokensBought  string `protobuf:"bytes,2,opt,name=tokens_bought,json=tokensBought,proto3" json:"tokens_bought,omitempty"`
	PricePerToken string `protobuf:"bytes,3,opt,name=price_per_token,json=pricePerToken,proto3" json:"price_per_token,omitempty"`
	SegmentCost   string `protobuf:"bytes,4,opt,name=segment_cost,json=segmentCost,proto3" json:"segment_cost,omitempty"`
}

func (m *SegmentPurchase) Reset()         { *m = SegmentPurchase{} }
func (m *SegmentPurchase) String() string { return proto.CompactTextString(m) }
func (*SegmentPurchase) ProtoMessage()    {}
func (*SegmentPurchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2f50e7843e7310, []int{3}
}
func (m *SegmentPurchase) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SegmentPurchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SegmentPurchase.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SegmentPurchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentPurchase.Merge(m, src)
}
func (m *SegmentPurchase) XXX_Size() int {
	return m.Size()
}
func (m *SegmentPurchase) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentPurchase.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentPurchase proto.InternalMessageInfo

func (m *SegmentPurchase) GetSegmentNumber() uint64 {
	if m != nil {
		return m.SegmentNumber
	}
	return 0
}

func (m *SegmentPurchase) GetTokensBought() string {
	if m != nil {
		return m.TokensBought
	}
	return ""
}

func (m *SegmentPurchase) GetPricePerToken() string {
	if m != nil {
		return m.PricePerToken
	}
	return ""
}

func (m *SegmentPurchase) GetSegmentCost() string {
	if m != nil {
		return m.SegmentCost
	}
	return ""
}

// MsgBuyMaincoinResponse defines the MsgBuyMaincoinResponse message.
type MsgBuyMaincoinResponse struct {
	// total tokens bought across all segments
	TotalTokensBought string `protobuf:"bytes,1,opt,name=total_tokens_bought,json=totalTokensBought,proto3" json:"total_tokens_bought,omitempty"`
	// total amount paid
	TotalPaid string `protobuf:"bytes,2,opt,name=total_paid,json=totalPaid,proto3" json:"total_paid,omitempty"`
	// average price per token
	AveragePrice string `protobuf:"bytes,3,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	// breakdown by segment
	Segments []*SegmentPurchase `protobuf:"bytes,4,rep,name=segments,proto3" json:"segments,omitempty"`
	// remaining funds returned (if hit segment limit)
	RemainingFunds string `protobuf:"bytes,5,opt,name=remaining_funds,json=remainingFunds,proto3" json:"remaining_funds,omitempty"`
	// informational message
	Message string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *MsgBuyMaincoinResponse) Reset()         { *m = MsgBuyMaincoinResponse{} }
func (m *MsgBuyMaincoinResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBuyMaincoinResponse) ProtoMessage()    {}
func (*MsgBuyMaincoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2f50e7843e7310, []int{4}
}
func (m *MsgBuyMaincoinResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuyMaincoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuyMaincoinResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuyMaincoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuyMaincoinResponse.Merge(m, src)
}
func (m *MsgBuyMaincoinResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuyMaincoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuyMaincoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuyMaincoinResponse proto.InternalMessageInfo

func (m *MsgBuyMaincoinResponse) GetTotalTokensBought() string {
	if m != nil {
		return m.TotalTokensBought
	}
	return ""
}

func (m *MsgBuyMaincoinResponse) GetTotalPaid() string {
	if m != nil {
		return m.TotalPaid
	}
	return ""
}

func (m *MsgBuyMaincoinResponse) GetAveragePrice() string {
	if m != nil {
		return m.AveragePrice
	}
	return ""
}

func (m *MsgBuyMaincoinResponse) GetSegments() []*SegmentPurchase {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *MsgBuyMaincoinResponse) GetRemainingFunds() string {
	if m != nil {
		return m.RemainingFunds
	}
	return ""
}

func (m *MsgBuyMaincoinResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// MsgSellMaincoin defines the MsgSellMaincoin message.
type MsgSellMaincoin struct {
	Seller string     `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	Amount types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
}

func (m *MsgSellMaincoin) Reset()         { *m = MsgSellMaincoin{} }
func (m *MsgSellMaincoin) String() string { return proto.CompactTextString(m) }
func (*MsgSellMaincoin) ProtoMessage()    {}
func (*MsgSellMaincoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2f50e7843e7310, []int{5}
}
func (m *MsgSellMaincoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSellMaincoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSellMaincoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSellMaincoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSellMaincoin.Merge(m, src)
}
func (m *MsgSellMaincoin) XXX_Size() int {
	return m.Size()
}
func (m *MsgSellMaincoin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSellMaincoin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSellMaincoin proto.InternalMessageInfo

func (m *MsgSellMaincoin) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

func (m *MsgSellMaincoin) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// MsgSellMaincoinResponse defines the MsgSellMaincoinResponse message.
type MsgSellMaincoinResponse struct {
	// amount of testusd refunded
	AmountRefunded types.Coin `protobuf:"bytes,1,opt,name=amount_refunded,json=amountRefunded,proto3" json:"amount_refunded"`
}

func (m *MsgSellMaincoinResponse) Reset()         { *m = MsgSellMaincoinResponse{} }
func (m *MsgSellMaincoinResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSellMaincoinResponse) ProtoMessage()    {}
func (*MsgSellMaincoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e2f50e7843e7310, []int{6}
}
func (m *MsgSellMaincoinResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSellMaincoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSellMaincoinResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSellMaincoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSellMaincoinResponse.Merge(m, src)
}
func (m *MsgSellMaincoinResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSellMaincoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSellMaincoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSellMaincoinResponse proto.InternalMessageInfo

func (m *MsgSellMaincoinResponse) GetAmountRefunded() types.Coin {
	if m != nil {
		return m.AmountRefunded
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "mychain.maincoin.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "mychain.maincoin.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgBuyMaincoin)(nil), "mychain.maincoin.v1.MsgBuyMaincoin")
	proto.RegisterType((*SegmentPurchase)(nil), "mychain.maincoin.v1.SegmentPurchase")
	proto.RegisterType((*MsgBuyMaincoinResponse)(nil), "mychain.maincoin.v1.MsgBuyMaincoinResponse")
	proto.RegisterType((*MsgSellMaincoin)(nil), "mychain.maincoin.v1.MsgSellMaincoin")
	proto.RegisterType((*MsgSellMaincoinResponse)(nil), "mychain.maincoin.v1.MsgSellMaincoinResponse")
}

func init() { proto.RegisterFile("mychain/maincoin/v1/tx.proto", fileDescriptor_2e2f50e7843e7310) }

var fileDescriptor_2e2f50e7843e7310 = []byte{
	// 722 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x4a,
	0x14, 0x8d, 0xdb, 0x34, 0xef, 0x65, 0x92, 0x26, 0xea, 0xb4, 0x6a, 0xdd, 0xbc, 0xf7, 0xfc, 0x82,
	0xcb, 0x47, 0x55, 0xc0, 0x56, 0x82, 0x00, 0xa9, 0x0b, 0x04, 0xa9, 0x84, 0xd8, 0x04, 0x45, 0x6e,
	0xd9, 0xb0, 0xb1, 0xc6, 0xf6, 0xe0, 0x58, 0x8d, 0x3d, 0x96, 0x67, 0x1c, 0x35, 0x3b, 0xc4, 0x92,
	0x15, 0xfc, 0x8b, 0x2e, 0xbb, 0x80, 0x3d, 0xcb, 0x2e, 0x2b, 0x56, 0xac, 0x10, 0x6a, 0x17, 0xfd,
	0x1b, 0xc8, 0x33, 0x13, 0x37, 0x89, 0x52, 0xa9, 0x62, 0x13, 0x65, 0xce, 0x39, 0xf7, 0xde, 0x73,
	0xef, 0xdc, 0x31, 0xf8, 0x37, 0x1c, 0xb9, 0x7d, 0x14, 0x44, 0x66, 0x88, 0x82, 0xc8, 0x25, 0x41,
	0x64, 0x0e, 0x5b, 0x26, 0x3b, 0x32, 0xe2, 0x84, 0x30, 0x02, 0x57, 0x25, 0x6b, 0x8c, 0x59, 0x63,
	0xd8, 0x6a, 0xac, 0xa0, 0x30, 0x88, 0x88, 0xc9, 0x7f, 0x85, 0xae, 0xa1, 0xb9, 0x84, 0x86, 0x84,
	0x9a, 0x0e, 0xa2, 0xd8, 0x1c, 0xb6, 0x1c, 0xcc, 0x50, 0xcb, 0xe4, 0x7a, 0xc1, 0x6f, 0x48, 0x3e,
	0xa4, 0x7e, 0x96, 0x3f, 0xa4, 0xbe, 0x24, 0x36, 0x05, 0x61, 0xf3, 0x93, 0x29, 0x0e, 0x92, 0x5a,
	0xf3, 0x89, 0x4f, 0x04, 0x9e, 0xfd, 0x93, 0x68, 0x73, 0x9e, 0xdf, 0x18, 0x25, 0x28, 0x94, 0x71,
	0xfa, 0x37, 0x05, 0xd4, 0xbb, 0xd4, 0x7f, 0x13, 0x7b, 0x88, 0xe1, 0x1e, 0x67, 0xe0, 0x13, 0x50,
	0x46, 0x29, 0xeb, 0x93, 0x24, 0x60, 0x23, 0x55, 0x69, 0x2a, 0xdb, 0xe5, 0x8e, 0xfa, 0xfd, 0xcb,
	0xc3, 0x35, 0x59, 0xf0, 0x85, 0xe7, 0x25, 0x98, 0xd2, 0x7d, 0x96, 0x04, 0x91, 0x6f, 0x5d, 0x49,
	0xe1, 0x33, 0x50, 0x12, 0xb9, 0xd5, 0x85, 0xa6, 0xb2, 0x5d, 0x69, 0xff, 0x63, 0xcc, 0x19, 0x88,
	0x21, 0x8a, 0x74, 0xca, 0xa7, 0x3f, 0xff, 0x2f, 0x1c, 0x5f, 0x9e, 0xec, 0x28, 0x96, 0x8c, 0xda,
	0x7d, 0xfc, 0xe1, 0xf2, 0x64, 0xe7, 0x2a, 0xdf, 0xc7, 0xcb, 0x93, 0x1d, 0x7d, 0xdc, 0xc0, 0xd1,
	0x55, 0x0b, 0x33, 0x76, 0xf5, 0x4d, 0xb0, 0x31, 0x03, 0x59, 0x98, 0xc6, 0x24, 0xa2, 0x58, 0x3f,
	0x04, 0xb5, 0x2e, 0xf5, 0x3b, 0xe9, 0xa8, 0x2b, 0x83, 0xe1, 0x1a, 0x58, 0x72, 0xd2, 0x11, 0x4e,
	0x44, 0x5f, 0x96, 0x38, 0xc0, 0xa7, 0xa0, 0x84, 0x42, 0x92, 0x46, 0x4c, 0x3a, 0xdf, 0x34, 0x64,
	0xaf, 0xd9, 0x15, 0x19, 0xf2, 0x8a, 0x8c, 0x3d, 0x12, 0x44, 0x9d, 0x62, 0xe6, 0xdb, 0x92, 0xf2,
	0x5d, 0x90, 0x59, 0x16, 0x49, 0xf4, 0x63, 0x05, 0xd4, 0xf7, 0xb1, 0x1f, 0xe2, 0x88, 0xf5, 0xd2,
	0xc4, 0xed, 0x23, 0x8a, 0xe1, 0x1d, 0x50, 0xa3, 0x02, 0xb2, 0xa3, 0x34, 0x74, 0x64, 0xdd, 0xa2,
	0xb5, 0x2c, 0xd1, 0xd7, 0x1c, 0x84, 0x5b, 0x60, 0x99, 0x91, 0x43, 0x1c, 0x51, 0xdb, 0x21, 0xa9,
	0xdf, 0x17, 0x36, 0xca, 0x56, 0x55, 0x80, 0x1d, 0x8e, 0xc1, 0xbb, 0xa0, 0x1e, 0x27, 0x81, 0x8b,
	0xed, 0x18, 0x27, 0x36, 0x67, 0xd4, 0x45, 0x2e, 0x5b, 0xe6, 0x70, 0x0f, 0x27, 0x07, 0x19, 0x08,
	0x6f, 0x81, 0xea, 0xb8, 0xa6, 0x4b, 0x28, 0x53, 0x8b, 0x5c, 0x54, 0x91, 0xd8, 0x1e, 0xa1, 0x4c,
	0xff, 0xbc, 0x00, 0xd6, 0xa7, 0x07, 0x33, 0x1e, 0x19, 0x34, 0xc0, 0x2a, 0x23, 0x0c, 0x0d, 0xec,
	0x69, 0x43, 0x62, 0x5c, 0x2b, 0x9c, 0x3a, 0x98, 0x74, 0xf5, 0x1f, 0x00, 0x42, 0x1f, 0xa3, 0xc0,
	0x93, 0xbe, 0xcb, 0x1c, 0xe9, 0xa1, 0xc0, 0xcb, 0x3a, 0x43, 0x43, 0x9c, 0x20, 0x1f, 0xdb, 0xdc,
	0xa5, 0xb4, 0x5c, 0x95, 0x60, 0x2f, 0xc3, 0xe0, 0x73, 0xf0, 0xb7, 0x74, 0x47, 0xd5, 0x62, 0x73,
	0x71, 0xbb, 0xd2, 0xbe, 0x3d, 0x77, 0x75, 0x66, 0xa6, 0x6b, 0xe5, 0x51, 0xf0, 0x1e, 0xa8, 0x27,
	0x38, 0x93, 0x06, 0x91, 0x6f, 0xbf, 0x4b, 0x23, 0x8f, 0xaa, 0x4b, 0xbc, 0x50, 0x2d, 0x87, 0x5f,
	0x66, 0x28, 0x54, 0xc1, 0x5f, 0x21, 0xa6, 0x14, 0xf9, 0x58, 0x2d, 0x71, 0xc1, 0xf8, 0xa8, 0x13,
	0xfe, 0x10, 0xf6, 0xf1, 0x60, 0x90, 0x2f, 0xcb, 0x3a, 0x28, 0x51, 0x3c, 0x18, 0xe4, 0xdb, 0x22,
	0x4f, 0x7f, 0xbe, 0x2e, 0x95, 0x6c, 0x5d, 0x64, 0x16, 0xdd, 0xe5, 0x7b, 0x3b, 0x59, 0x30, 0xbf,
	0x84, 0x57, 0xa0, 0x2e, 0x22, 0xec, 0x04, 0x67, 0xdd, 0x60, 0x8f, 0x3b, 0xb8, 0x41, 0xa5, 0x9a,
	0x88, 0xb3, 0x64, 0x58, 0xfb, 0xeb, 0x02, 0x58, 0xec, 0x52, 0x1f, 0x3a, 0xa0, 0x3a, 0xf5, 0xc6,
	0xe7, 0x0f, 0x78, 0xe6, 0x1d, 0x35, 0x1e, 0xdc, 0x44, 0x95, 0xbb, 0xb6, 0x41, 0x65, 0xf2, 0xa9,
	0x6d, 0x5d, 0x17, 0x3c, 0x21, 0x6a, 0xdc, 0xbf, 0x81, 0x28, 0x2f, 0xe0, 0x80, 0xea, 0xd4, 0xfd,
	0x5c, 0xdb, 0xc4, 0xa4, 0xea, 0xfa, 0x26, 0xe6, 0x8d, 0xbe, 0xb1, 0xf4, 0x3e, 0xfb, 0x26, 0x75,
	0xda, 0xa7, 0xe7, 0x9a, 0x72, 0x76, 0xae, 0x29, 0xbf, 0xce, 0x35, 0xe5, 0xd3, 0x85, 0x56, 0x38,
	0xbb, 0xd0, 0x0a, 0x3f, 0x2e, 0xb4, 0xc2, 0x5b, 0x75, 0xce, 0x27, 0x89, 0x8d, 0x62, 0x4c, 0x9d,
	0x12, 0xff, 0xa4, 0x3e, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x05, 0x17, 0x77, 0xda, 0x26, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// BuyMaincoin defines the BuyMaincoin RPC.
	BuyMaincoin(ctx context.Context, in *MsgBuyMaincoin, opts ...grpc.CallOption) (*MsgBuyMaincoinResponse, error)
	// SellMaincoin defines the SellMaincoin RPC.
	SellMaincoin(ctx context.Context, in *MsgSellMaincoin, opts ...grpc.CallOption) (*MsgSellMaincoinResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/mychain.maincoin.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BuyMaincoin(ctx context.Context, in *MsgBuyMaincoin, opts ...grpc.CallOption) (*MsgBuyMaincoinResponse, error) {
	out := new(MsgBuyMaincoinResponse)
	err := c.cc.Invoke(ctx, "/mychain.maincoin.v1.Msg/BuyMaincoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SellMaincoin(ctx context.Context, in *MsgSellMaincoin, opts ...grpc.CallOption) (*MsgSellMaincoinResponse, error) {
	out := new(MsgSellMaincoinResponse)
	err := c.cc.Invoke(ctx, "/mychain.maincoin.v1.Msg/SellMaincoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// BuyMaincoin defines the BuyMaincoin RPC.
	BuyMaincoin(context.Context, *MsgBuyMaincoin) (*MsgBuyMaincoinResponse, error)
	// SellMaincoin defines the SellMaincoin RPC.
	SellMaincoin(context.Context, *MsgSellMaincoin) (*MsgSellMaincoinResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) BuyMaincoin(ctx context.Context, req *MsgBuyMaincoin) (*MsgBuyMaincoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyMaincoin not implemented")
}
func (*UnimplementedMsgServer) SellMaincoin(ctx context.Context, req *MsgSellMaincoin) (*MsgSellMaincoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellMaincoin not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mychain.maincoin.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BuyMaincoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBuyMaincoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BuyMaincoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mychain.maincoin.v1.Msg/BuyMaincoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BuyMaincoin(ctx, req.(*MsgBuyMaincoin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SellMaincoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSellMaincoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SellMaincoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mychain.maincoin.v1.Msg/SellMaincoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SellMaincoin(ctx, req.(*MsgSellMaincoin))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mychain.maincoin.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "BuyMaincoin",
			Handler:    _Msg_BuyMaincoin_Handler,
		},
		{
			MethodName: "SellMaincoin",
			Handler:    _Msg_SellMaincoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mychain/maincoin/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgBuyMaincoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuyMaincoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuyMaincoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SegmentPurchase) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SegmentPurchase) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SegmentPurchase) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SegmentCost) > 0 {
		i -= len(m.SegmentCost)
		copy(dAtA[i:], m.SegmentCost)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SegmentCost)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PricePerToken) > 0 {
		i -= len(m.PricePerToken)
		copy(dAtA[i:], m.PricePerToken)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PricePerToken)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TokensBought) > 0 {
		i -= len(m.TokensBought)
		copy(dAtA[i:], m.TokensBought)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TokensBought)))
		i--
		dAtA[i] = 0x12
	}
	if m.SegmentNumber != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SegmentNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgBuyMaincoinResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuyMaincoinResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuyMaincoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.RemainingFunds) > 0 {
		i -= len(m.RemainingFunds)
		copy(dAtA[i:], m.RemainingFunds)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RemainingFunds)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Segments) > 0 {
		for iNdEx := len(m.Segments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Segments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.AveragePrice) > 0 {
		i -= len(m.AveragePrice)
		copy(dAtA[i:], m.AveragePrice)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AveragePrice)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TotalPaid) > 0 {
		i -= len(m.TotalPaid)
		copy(dAtA[i:], m.TotalPaid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TotalPaid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TotalTokensBought) > 0 {
		i -= len(m.TotalTokensBought)
		copy(dAtA[i:], m.TotalTokensBought)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TotalTokensBought)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSellMaincoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSellMaincoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSellMaincoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Seller) > 0 {
		i -= len(m.Seller)
		copy(dAtA[i:], m.Seller)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Seller)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSellMaincoinResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSellMaincoinResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSellMaincoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AmountRefunded.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgBuyMaincoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *SegmentPurchase) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SegmentNumber != 0 {
		n += 1 + sovTx(uint64(m.SegmentNumber))
	}
	l = len(m.TokensBought)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PricePerToken)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SegmentCost)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBuyMaincoinResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TotalTokensBought)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TotalPaid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AveragePrice)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Segments) > 0 {
		for _, e := range m.Segments {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.RemainingFunds)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSellMaincoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Seller)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSellMaincoinResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AmountRefunded.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuyMaincoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuyMaincoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuyMaincoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SegmentPurchase) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SegmentPurchase: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SegmentPurchase: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SegmentNumber", wireType)
			}
			m.SegmentNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SegmentNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokensBought", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokensBought = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PricePerToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PricePerToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SegmentCost", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SegmentCost = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuyMaincoinResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuyMaincoinResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuyMaincoinResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalTokensBought", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalTokensBought = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalPaid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalPaid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AveragePrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AveragePrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Segments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Segments = append(m.Segments, &SegmentPurchase{})
			if err := m.Segments[len(m.Segments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingFunds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemainingFunds = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSellMaincoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSellMaincoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSellMaincoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSellMaincoinResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSellMaincoinResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSellMaincoinResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountRefunded", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountRefunded.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
